services:
  postgres:
    image: postgres:16
    container_name: bd_tp_procesos
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: procesos
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Archivos .sql o .sh aqu√≠ se ejecutan al primer arranque:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d procesos || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data:
